import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// importing styles:
import './cssStyling/createEditTrivias.css';
import './cssStyling/dashboardstyling.css';
import './cssStyling/editTriviastyling.css';
import './cssStyling/homepagestyling.css';
import './cssStyling/howToPlay.css';
import './cssStyling/playTrivia.css';
import './cssStyling/ProfilePicture.css';
import './cssStyling/shareTrivia.css';
import './cssStyling/triviaEndScreen.css';
import './cssStyling/viewSharedTrivias.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
